### ISSUE TITLE
would you mind submitting pocketNes code sources, per version?

### ISSUE THREAD

**Issue by cotodevel** [Dwedit/PocketNES#1]
Not really an issue, heh.

An user requested that I update the pocketNes CPU core in NesDS, but before I go adding some 2013'ish version there. Is there any source that I can use as base, where I can more or less see supported games or known  glitches?

git versioning is perfect for this kind of task, so users (beta testers) would keep a list of known working games, then I could update Nes cores just fine inmediately excluding any bugs that may arise pre-port or post-port

Thanks.

**Comment by Dwedit** [comment]
There are so many changes between PocketNES right before the NesDS fork and
PocketNES afterwards.  But the CPU core by itself is much easier to move
than the whole thing.

Do you need earlier versions of the source code?  Built for GCC or for
other compilers?

**Comment by cotodevel** [comment]
Well perhaps a way to keep each PocketNES core (sources as whole, cpu, io, memory, vram) + a list of known games, even implemented mappers as separate git branches. So if someone like me would take pieces more or less would know if certain bugs arise due to port or due to core behaviour.

For that the git here could be of help for you, and you'd need some beta testers to test each game in per PocketNes version (release) so everything is somewhat documented.

As for the code itself, is no problem. But I think git has helped me so much to bring DS homebrew to ToolchainGenericDS, and I feel it could be of the same help for your projects. 

So then, I would pick the best version, and merge into NesDS. Because coding in the blind takes too much time and little gain... documenting stuff is much better imho

Thank you!

**Comment by Dwedit** [comment]
The biggest breaking change was when I went from a scanline-by-scanline system to a purely Timestamp based system.  Doing this significantly increased accuracy and performance, but broke compatibility with all the older code.

**Comment by cotodevel** [comment]
the NesDS, uses nds vblank irq to render per scanline (pocketnes), to perform nes ppu writes per scanline, then each line spawns a mapper handle, that also depend on the scanline count. A mapper will write characters to nds vram region on its own. 

So the method used for rendering is the old. That's why I suggested that stuff earlier.

**Comment by cotodevel** [comment]
i'm closing the "never was" issue lol. Cheers.
