### ISSUE TITLE
Some build config fixes

### ISSUE THREAD

**Issue by clbr** [Dwedit/PocketNES#10]
The hexn, hex8 and number functions are also used by the crash checker. If CHEATFINDER and EDITFOLLOW are disabled, the build currently fails. Please see https://github.com/clbr/pocketnes/commit/90594a05bc3b9ab3b076be1cd900968642739792 for which parts need an additional "| CRASH" check (the inline change was specific to my toolchain, so you may not want to take that part).

**Comment by Dwedit** [comment]
Fixed `hexn` and `number` having the wrong flags for being built in.
