### ISSUE TITLE
Failing to compile on Windows and MacOS

### ISSUE THREAD

**Issue by grendell** [Dwedit/PocketNES#11]
I just installed devkitPro and gba-dev, and attempted to run `make`.  Tried on both f7e7cbb and 1ae2741.

```
% make
cache.c
In file included from /opt/devkitpro/libgba/include/gba.h:41,
                 from /Users/grayson/projects/ext/PocketNES/src/gba.h:7,
                 from /Users/grayson/projects/ext/PocketNES/src/includes.h:8,
                 from /Users/grayson/projects/ext/PocketNES/src/cache.c:1:
/opt/devkitpro/libgba/include/gba_systemcalls.h: In function 'BiosCheckSum':
/opt/devkitpro/libgba/include/gba_systemcalls.h:102:29: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'asm'
  102 |         register u32 result asm("r0");
      |                             ^~~
/opt/devkitpro/libgba/include/gba_systemcalls.h:102:29: error: implicit declaration of function 'asm' [-Wimplicit-function-declaration]
/opt/devkitpro/libgba/include/gba_systemcalls.h:104:47: error: 'result' undeclared (first use in this function)
  104 |                 __asm ("SWI     0x0d" :  "=r"(result) :: "r1", "r2", "r3");
      |                                               ^~~~~~
/opt/devkitpro/libgba/include/gba_systemcalls.h:104:47: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [cache.o] Error 1
make: *** [build] Error 2
```

```
% gcc --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by Dwedit** [comment]
What does your "arm-none-eabi-gcc" say?  It should be that compiler, not the native gcc.

DevkitArm has very specific kinds of makefiles.  They include the line `include \$(DEVKITARM)/gba_rules`.  From there, 'gba_rules' includes 'base_rules', which includes 'base_tools'.  'base_tools' is responsible for defining $(CC) ($AS) ($LD) etc, they are defined using the prefix "arm-none-eabi-", so you get "arm-none-eabi-gcc" and "arm-none-eabi-g++", etc...

My own computer has version 11 of GCC installed.  If the compiler being used to build is the correct compiler, perhaps they changed the syntax for inline assembly at some point?

**Comment by grendell** [comment]
Ah, apologies, I see the CC definition in base_tools now.

```
% arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 9-2019-q4-major) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Dwedit** [comment]
That's an error when building libgba's own code, so something is going wrong here.  Try running `make SHELL='sh -x'` and that will make it display the name of every command it executes.

**Comment by grendell** [comment]
```
arm-none-eabi-gcc -MMD -MP -MF /Users/grayson/projects/ext/PocketNES/build/cache.d -g -Wall -Os -mcpu=arm7tdmi -mtune=arm7tdmi -fomit-frame-pointer -ffast-math -std=c99 -mthumb -mthumb-interwork -I/opt/devkitpro/libgba/include -I/Users/grayson/projects/ext/PocketNES/build -c /Users/grayson/projects/ext/PocketNES/src/cache.c -o cache.o
```

**Comment by Dwedit** [comment]
Okay, I see the exact same command (except for different pathnames) when I build it, so 'make' itself is working okay.

I'm a bit stumped here, first try running the Msys shell (`C:\devkitpro\msys2\msys2.exe` on my PC) and run `pacman -Syu` a couple times to upgrade all the packages.  After upgrading, my version of gcc became 11.1.0.

If that doesn't work, rename your devkitpro directory to something like devkitpro-old and try reinstalling.

**Comment by Dwedit** [comment]
I see a thumbs up reaction, does that mean that everything is all fixed and I can close the issue?

**Comment by grendell** [comment]
No, sorry, that was a "I'll try it and let you know."  No luck on MacOS, reinstalling on Windows now.

**Comment by grendell** [comment]
Same results on Windows, unfortunately.  Just to check:
```
$ $DEVKITARM/bin/arm-none-eabi-gcc --version
arm-none-eabi-gcc.exe (devkitARM release 64) 14.1.0
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by grendell** [comment]
Should I try a version of [devkitPro Updater](https://github.com/devkitPro/installer/releases/tag/v3.0.3) before v3.0.3?

Edit:  oh, I suppose not:
> The version number here refers to the installer and has no relevance to any of the toolchains or other components we supply.

**Comment by Dwedit** [comment]
Seems like your "gba_systemcalls.h" file might be out of date.  Would need to update your copy of Libgba.

My copy has this definition for BiosCheckSum:

```
//---------------------------------------------------------------------------------
static inline u32 BiosCheckSum() {
//---------------------------------------------------------------------------------
	register u32 result;
	#if	defined	( __thumb__ )
		__asm ("SWI	0x0d\nmov %0,r0\n" :  "=r"(result) :: "r1", "r2", "r3");
	#else
		__asm ("SWI	0x0d<<16\nmov %0,r0\n" : "=r"(result) :: "r1", "r2", "r3");
	#endif
	return result;
}
```

It does not try to do `asm("r0");` at any point.

**Comment by grendell** [comment]
But how could that be when I just downloaded the devkitPro updater today on two separate machines?  According to their docs:
>This is the installer provided by devkitPro which installs and updates the tools and libraries we provide and support.

>Please do not use this installer and then overwrite anything with downloads provided by 3rd parties. Downgrading individual components can and will cause problems with your installation.

I don't want to break your dev environment, but have you tried building with the latest version of devkitPro?

**Comment by grendell** [comment]
Looks like it was changed in libgba in April 2021:  https://github.com/devkitPro/libgba/commit/c6492aa1bb695793b9d682c94a075f96370d4262
and persists to latest:  https://github.com/devkitPro/libgba/blame/master/include/gba_systemcalls.h#L102

**Comment by Dwedit** [comment]
Looks like using `asm` and `-std=c99` at the same time is now forbidden.  I'll take `-std=c99` out of the makefile.

Linkscript also needs changing too...

edit: The code to fix the makefile, linkscript, and c files has been pushed.

Using `-std=c99` disables the `asm` keywords, but `-std=gnu99` allows it, changed to that.

Linkscript needed a minor fix to fix that the "ewram_data" section wasn't properly going into any memory block.

C files needed minor changes, because GCC now gives errors if the pointer types do not match the functions.  Just a bit of casting.

**Comment by grendell** [comment]
Awesome, thanks!  Although now I'm running into this (hopefully an easier solve):
`/Users/grayson/projects/ext/PocketNES/src/bindata.s:26: Error: file not found: ../pocketnes_mb.gba`

**Comment by Dwedit** [comment]
Build the multiboot version first, `make -f makefile_mb`.  Main version depends on Multiboot version existing because of the "Go Multiboot" feature.  I should come up with a way to fix that, but I suck at having one makefile call another makefile.

**Comment by grendell** [comment]
Awesome, thank you for the troubleshooting!

**Comment by Dwedit** [comment]
Makefile now builds multiboot version first.
