### ISSUE TITLE
ROMMENU 0 creates a broken emu

### ISSUE THREAD

**Issue by clbr** [Dwedit/PocketNES#9]
If I disable ROMMENU, everything else staying the same, the resulting build blackscreens. It stays interactive however - L+R loads the menu. Trying to track down why it fails. At least it seems to load the ROM correctly, mapper_number was correct.

**Comment by clbr** [comment]
The bug is in loadcart.c.

**Comment by clbr** [comment]
In loadcart.c, non-compy build, commenting out the "if (!ROMMENU && comptype == 0 && compsrc<(u8*)0x08000000)" and removing the ROMMENU check from the next if fixes this.

**Comment by Dwedit** [comment]
I just tested the non-fixed version, and it only worked if the ROM was compressed.  Had junk on the UI tilemap.

**Comment by clbr** [comment]
Yes, my ROM is uncompressed.

**Comment by clbr** [comment]
Fixed in git.
